#'
#' ProcWAS Manhattan Plotting
#' Generates a PheWAS Manhattan plot with phenotypes on the x-axis and p-values on a -log10 scale on the y-axis. This function visualizes the results generated by the phewas_ext() function that performs the ProcWAS analysis.
#' 
#' @param d This will typically be the output data frame from the phewas_ext() function (i.e., the PheWAS results), although this can also be a user-specified data frame with phenotype, OR, and p columns. The phenotype column should contain the phecodes, not the phecode descriptions. The name of the OR column needs to be capitalized (i.e., “OR” not “or”).
#' @param suggestive.line The p-value at which to draw a blue line to show a significance threshold. The default value is 0.05. An NA value results in no line.
#' @param significant.line The p-value at which to draw a red line to show an adjusted significance threshold. The default applies a Bonferroni correction. An NA value results in no line.
#' @param annotate.level The p-value threshold for annotating phenotypes on the Manhattan plot. The default value is that provided in the significant.line argument.
#' @param y.axis.interval The interval used for the y-axis of the Manhattan plot (default value = 5).
#' @return This function returns a Manhattan Plot with a log(10) y axis and phenotypes as the x axis.
#' @source https://github.com/monikagrabowska/PedsPheWAS/blob/main/R/plotManhattan.R
#' @source https://github.com/PheWAS/PheWAS/blob/master/R/phewasManhattan.R
#' @export

plotManhattan <-
  function(d, suggestive.line=0.05, significant.line,
           annotate.level,
           y.axis.interval=5,
           ...) {
    if(sum(c("phenotype","p") %in% names(d))<2 ) stop("Data input must contain columns phenotype and p.")
    if(!length(d$OR)) stop("OR not provided in data input.")
    
    #Remove records with NA p values
    d=d[!is.na(d$p),]
    
    #Transform the significance thresholds
    if(missing(significant.line)) significant.line=suggestive.line/nrow(d)
    significant.line=-log10(significant.line)
    suggestive.line=-log10(suggestive.line)
    if(missing(annotate.level)) {
      if(is.na(significant.line)) {annotate.level=-log10(min(d$p,na.rm=T))}
      else{annotate.level=significant.line}
    }
    else {annotate.level=-log10(annotate.level)}
    
    #Nudge all of the p=0 results to the smallest double
    if(sum(d$p==0)>0)d[d$p==0,]$p=.Machine$double.xmin
    
    #Restrict to only those with appropriate p-values
    d=d[d$p>0 & d$p<=1,]
    
    #Create the - log p value for plotting. No errors given restriction to p>0
    d$value = -log10(d$p)
    
    max.y=max(ceiling(max(d$value)),4.4)
    
    y.axis.label=expression(-log[10](italic(p)))
    
    sizing=FALSE
    
    #Create OR direction
    d$direction = d$OR>=1
    
    plot=phenotypePlot(d,suggestive.line=suggestive.line,significant.line=significant.line,
                       annotate.level=annotate.level,
                       y.axis.interval=y.axis.interval,
                       ...)   
  }